---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."

autologin: True

publisher: ndv
org: koya_law
show: rework1
room_name: room_1

streaming:
  method: null

irc:
  network: freenode
  server: irc.freenode.net
  ssl_port: 6697
  global_channels:
  - "#TimVideos"
  - "#PumpingStationOne"

irc_autostart: false

upload_formats: ['mp4']

time_zone: America/Pacific

frequency: 60

domain: home

apt_proxy: true

# Git repos:
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
# playbook_repo: https://github.com/CarlFK/video-stack-deploy.git
playbook_branch: master

# inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_repo: https://github.com/CarlFK/video-stack-bin-chicken.git
inventory_repo_dir: cboxs


voctomix:
  display_system: x
  framerate: 30
  previews: false
  autostart_gui: false
  # loop_url: None

blackmagic:
    urls:
    - http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.4/deb/x86_64/desktopvideo_11.4a14_amd64.deb
    - http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.4/deb/x86_64/desktopvideo-gui_11.4a14_amd64.deb
    - http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.4/deb/x86_64/mediaexpress_3.6a13_amd64.deb
    - http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.4/deb/x86_64/desktopvideo-scanner_11.4a14_amd64.deb
    dkms_version: 11.4a14

blackmagic_default_mode: 720p5994

blackmagic_sources:
- card: 0
  connection: hdmi
  mode: 720p5994
  audio: true

serial_terminal:
- tio
- cu
#- flterm

sources:
- Camera
- Grabber

rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png

# what the pxe server can install
ubuntu_suites: []

veyepar_url: http://veyepar.nextdayvideo.com

