---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."

autologin: True

publisher: ndv
org: fossi
show: latch_2019

streaming:
  method: null

irc:
  autostart: false
  network: freenode
  server: irc.freenode.net
  ssl_port: 6697
  global_channels:
  - "#TimVideos"
  - "#PumpingStationOne"

irc_room_channel: "PyTexas"
irc_nick: CboxX

upload_formats: ['mp4']

time_zone: US/Chicago

frequency: 60

domain: home

apt_proxy: true

staticips:
  write_hosts: false
  write_interfaces: false
  hosts:

    - hostname: gator
      ip: 10.20.0.20
    - hostname: odroid1
      ip: 10.20.0.21

    - hostname: cnt5
      ip: 10.20.0.20

    - hostname: cnt6
      ip: 10.20.0.30
    - hostname: odroid3
      ip: 10.20.0.31

    - hostname: dc10b
      ip: 10.20.0.3


# Git repos:
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
# playbook_repo: https://github.com/CarlFK/video-stack-deploy.git
playbook_branch: master

# inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_repo: https://github.com/CarlFK/video-stack-bin-chicken.git
inventory_repo_dir: cboxs

blackmagic_default_mode: 720p5994

blackmagic:
    urls:
        desktopvideo: http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.2/deb/x86_64/desktopvideo_11.2a8_amd64.deb
        # desktopvideo_gui: http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.2/deb/x86_64/desktopvideo-gui_11.2a8_amd64.deb
        # mediaexpress: http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.2/deb/x86_64/mediaexpress_3.5.9a10_amd64.deb
        scanner: http://pc8/blackmagic/Blackmagic_Desktop_Video_Linux_11.2/deb/x86_64/desktopvideo-scanner_11.2a8_amd64.deb
    dkms_version: 11.2a8

voctomix:
  display_system: x
  framerate: 30
  previews: false
  autostart_gui: false
  loop_url: http://pc8/assets/loop.ts


serial_terminal:
- tio
- cu
#- flterm

sources:
- Camera
- Grabber

rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png

# what the pxe server can install
ubuntu_suites: [trusty, xenial, artful, bionic, ]

veyepar_url: http://veyepar.nextdayvideo.com

