---
debian_version: buster
conference_name: Example Conference
streaming:
  frontend:
    data_root: /srv/streaming-frontend
    # onsite: groot.online.debconf.org
    onsite: veyepar.nextdayvideo.com
  backend:
    data_root: /srv/streaming
    # server_name: groot.online.debconf.org
    server_name: veyepar.nextdayvideo.com
    rtmp_push_uris:
      - rtmp://veyepar.nextdayvideo.com/front
        # - rtmp://groot.online.debconf.org/front
    ips:
      - "172.26.11.59"
  rooms:
    - buzz
    - rex
    - bo
  dump: True
  rtmp_publishers:
    - 0.0.0.0/0
  hq_config:
    hls_bandwidth: 2176000
    video_bitrate: 2000  # kbps
    audio_bitrate: 128000  # bps
    keyframe_period: 60  # seconds
    width: 1280
  adaptive:
    video_codec: libx264
    audio_codec: aac
    variants:
      high:
        hls_bandwidth: 1152000
        video_bitrate: 1024k
        audio_bitrate: 128k
        extra_settings: -tune zerolatency -preset veryfast -crf 23
        width: 900
      mid:
        hls_bandwidth: 448000
        video_bitrate: 768k
        audio_bitrate: 96k
        extra_settings: -tune zerolatency -preset veryfast -crf 23
        width: 720
      low:
        hls_bandwidth: 288000
        video_bitrate: 256k
        audio_bitrate: 48k
        extra_settings: -tune zerolatency -preset veryfast -crf 23
        width: 480
  mix_channels: false
  method: rtmp
  rtmp:
    vaapi: false
    location: "rtmp://backend.live.debconf.org:1935/stream/{{ room_name }} live=1"
  geoip:
    domain: live.debconf.org
    rules:
    - continent: [NA, SA, AN]
      target: sfo2

# Centralized letsencrypt challenges
letsencrypt_well_known_dir: /var/www/well-known

skip_unit_test: false

