---

- name: install R&D related packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - vim
        # - vizzini-dkms
      # for mode-switch:
        # - flterm
      - tio
      # hwinfo --monitor shows   Model: "HDMI2USB-2"
      - hwinfo
        # help carl reimage
      # for testing
      - mplayer
      # to display hdmi2usb
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-good
      - gstreamer1.0-libav
      - frei0r-plugins
      - gstreamer1.0-tools
      - python-wxgtk3.0
      # for making python venvs
      - python3-venv
      # for moutning random usb drives
      - pmount
      # for moutning random boxes
      - sshfs
      - cstream
      # hdmi2usb bandwith monitor
      # https://github.com/aguinet/usbtop
      - memtest86+

- name: install grub-ipxe on Ubuntu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - grub-ipxe
  when: ansible_distribution == 'Ubuntu'

- name: install grub-ipxe on Debian
  apt:
    deb: "{{ item }}"
  with_items:
    - https://launchpad.net/ubuntu/+archive/primary/+files/grub-ipxe_1.0.0+git-20190109.133f4c4-0ubuntu2_all.deb
  when: ansible_distribution == 'Debian'

- name: Create ~/bin and ~/temp dir
  file:
    state: directory
    path: /home/{{ user_name }}/{{ item }}
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_list:
  - bin
  - temp

- name: git clone bunch of things
  git:
    repo: "https://github.com/{{ item[0] }}/{{ item[1] }}.git"
    dest: "/home/{{ user_name }}/{{ item[1] }}"
    # depth: 1
    force: yes
  become: true
  become_user: "{{ user_name }}"
  with_list:
      # - [timvideos, HDMI2USB-mode-switch]
      # - [timvideos, HDMI2USB-litex-firmware]
    # - [timvideos, HDMI2USB-firmware-prebuilt]
  - [CarlFK, clocky]
  - [CarlFK, voctomix-outcasts]
  - [aguinet, usbtop]


- lineinfile:
    path: /home/{{ user_name }}/.bashrc
    regexp: '^export DISPLAY='
    line: 'export DISPLAY=:0.0'
  tags:
    - display
