---
room_name: calypso

# video_disk: /dev/sda1

blackmagic_sources:
- card: 0
  connection: hdmi
  mode: 720p5994
  audio: true

xingest_sources:
  - description: "knockoff gopro uvc cam"
    src: "v4l2src device=/dev/video2 ! queue ! decodebin ! videoconvert ! videorate ! videoscale ! {videocaps} ! mux. audiotestsrc wave=ticks freq=330 ! {audiocaps} ! queue ! matroskamux name=mux !"
    port: 10003
  - description: "test pattern: bars and beeps"
    video_source: test
    video_attribs: pattern=smpte
    audio_source: test
    audio_attribs: wave=ticks
    port: 10000
  - description: "test pattern: ball and white-noise"
    video_source: test
    video_attribs: pattern=ball
    audio_source: test
    audio_attribs: wave=white-noise
    port: 10001
  - description: "test pattern: viz and beep"
    video_source: spacescope
    video_attribs:
    audio_source: test
    audio_attribs: wave=ticks
    port: 10002
