---
# ansible_python_interpreter: /usr/bin/python3
# skip_unit_test: False
# run_django_collectstatic: True

user_name: videoteam
# user_name: pi
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."
ssh_password_auth: true

# db_password: changeme

autologin: True

publisher: ndv
org: ndv
show: PyOhio_2024
# room_name: room_1

irc:
  network: libre.chat
  server: irc.libe.chat
  ssl_port: 6697
  global_channels:
  - "#TimVideos"
  - "#PumpingStationOne"

irc_autostart: false

upload_formats: ['mp4']

time_zone: US/Eastern

frequency: 60

domain: home.net

apt_proxy: false

# Git repos:
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
# playbook_repo: https://github.com/CarlFK/video-stack-deploy.git
playbook_branch: master

# inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_repo: https://github.com/CarlFK/video-stack-bin-chicken.git
inventory_repo_dir: inventory

mixer:
  mirrors: true
  display_system: gl
  framerate: 30
  previews: false
  autostart_gui: true
  # streaming.method: rtmp
  # loop_url: None

# letsencrypt_account_email: carl@NextDayVideo.com

blackmagic:
  urls:
    desktopvideo: http://veyepar.nextdayvideo.com/bm/Blackmagic_Desktop_Video_Linux_12.7.1/deb/x86_64/desktopvideo_12.7.1a1_amd64.deb
    desktopvideo_gui: http://veyepar.nextdayvideo.com/bm/Blackmagic_Desktop_Video_Linux_12.7.1/deb/x86_64/desktopvideo-gui_12.7.1a1_amd64.deb
    mediaexpress: http://veyepar.nextdayvideo.com/bm/Blackmagic_Desktop_Video_Linux_12.7.1/deb/x86_64/mediaexpress_3.8.1a4_amd64.deb
  dkms_version: 12.7.1a1

blackmagic_default_mode: 720p5994

blackmagic_sources:
- card: 0
  connection: hdmi
  mode: 720p5994
  audio: true

serial_terminal:
- tio
#- cu
#- flterm

sources:
- Camera1
- Grabber

rsync_local_dest: /mnt/disk/Videos/veyepar/
rsync_excludes:
- 0[0-7]*.ts
- 19*.ts
- 2[0-3]*.ts

# what the pxe server can install
ubuntu_suites: []

debian_version: bookworm

veyepar_url: http://veyepar.NextDayVideo.com


