---
- name: install conky
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - conky
      - conky-all
      - lm-sensors
  tags:
      - conky

- name: Create dirs
  file:
    state: directory
    path: "/home/{{ user_name }}/.config/{{ item }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_items:
    - conky
    - autostart
  tags:
    - conky

- name: put conf in place
  template:
    src: templates/conkyrc.j2
    dest: /home/{{ user_name }}/.config/conky/conky.conf
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  tags:
      - conky

- name: put autostart file in place
  copy:
    src: files/conky.desktop
    dest: "/home/{{ user_name }}/.config/autostart"
  tags:
      - conky
